### ISSUE TITLE
snaps

### ISSUE THREAD

**Issue by krzemienski** [teejee2008/aptik-gtk#6]
**Describe the solution you'd like**
Would love for the ability to backup all installed snaps, since now adays things like slack / my ides and the basic tools I tend to install from snaps due to simplicity currently i run after having finished an --restore-all

```
#!/bin/bash

sudo apt install synaptic

sudo apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common

sudo snap install intellij-idea-ultimate --classic
sudo snap install postman
sudo snap install gitkraken
sudo snap install slack --classic
sudo snap install atom --classic
sudo snap install datagrip --classic
sudo snap install code --classic
sudo snap install go --classic
sudo snap install circleci
sudo snap install vlc
sudo snap install webhook
sudo snap install telegram-desktop
sudo snap install zenkit
sudo snap install goland --classic 
sudo snap install pycharm-professional --classic
sudo snap install noson
sudo snap install auryo
sudo snap install opera
sudo snap install termius-app
```

**Describe alternatives you've considered**
Using the --add on the --backup-all?

**Comment by teejee2008** [comment]
The free version of Aptik is no longer maintained

A paid version is available with more features.
https://teejeetech.in/2019/07/14/aptik-v19-07/
