### ISSUE TITLE
Static release of aptik-gtk?

### ISSUE THREAD

**Issue by Aufschlauer** [teejee2008/aptik-gtk#7]
**Is your feature request related to a problem? Please describe.**
I'm trying to use aptik-gtk on "Linux Mint 17.3 Rosa". But the installation failed with dependency problem:

```
Preparing to unpack aptik-gtk-v18.5.1-amd64.deb ...
Unpacking aptik-gtk (18.5.1) over (18.5.1) ...
dpkg: dependency problems prevent configuration of aptik-gtk:
 aptik-gtk depends on libgdk-pixbuf2.0-0 (>= 2.31.2); however:
  Version of libgdk-pixbuf2.0-0:amd64 on system is 2.30.7-0ubuntu1.8.
 aptik-gtk depends on libgtk-3-0 (>= 3.17.9); however:
  Version of libgtk-3-0:amd64 on system is 3.10.8~8+qiana.
 aptik-gtk depends on libvte-2.91-0; however:
  Package libvte-2.91-0 is not installed.
```

**Describe the solution you'd like**
A static release of aptik-gtk would solve the problem that older distributions are not supported - like mine.

**Describe alternatives you've considered**
I tried the oldest version of aptik-gtk (aptik-gtk-v18.5-amd64.deb) I found on the project side without success - still dependency problems.

**Comment by teejee2008** [comment]
The free version of Aptik is no longer maintained

A paid version is available with more features.

https://teejeetech.in/2019/07/14/aptik-v19-07/
